plugins {
    id 'java'
    id("io.freefair.lombok") version "8.12.2"
}

group 'io.testomat'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.10.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

dependencies {
    implementation 'io.github.cdimascio:java-dotenv:5.2.2'
    implementation('com.codeborne:selenide:7.6.1')
    implementation 'com.microsoft.playwright:playwright:1.49.0'
    implementation('org.slf4j:slf4j-simple:2.0.13')
    implementation 'com.github.javafaker:javafaker:1.0.2'
    implementation 'io.rest-assured:rest-assured:5.5.1'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.3'

    testImplementation 'org.assertj:assertj-core:3.27.3'
    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
}

test {
    useJUnitPlatform()
}
